### ISSUE TITLE
Incorrect ratio::abs() behavior for INTMAX_MIN

### ISSUE THREAD

**Issue by DymOK93** [DymOK93/KTL#121]
https://github.com/DymOK93/KTL/blob/master/include/ratio.hpp#L9

**Comment by GeorgyFirsov** [comment]
Seems it is a common implementation across main STL implementations.

Moreover it is an implementation detail, that is not available for direct usage. Maybe it is not quite necessary to fix such behaviour. Well, actually there's no good way to fix it without assigning a value to another type (e.g. `uintmax_t`)

Using unsigned type seems to be a good solution, because an absolute value is always non-negative, but what about semantics and expectations? As I can see, the result of `details::abs` is compared or assigned to a variable of a signed type. This case could be broken in such a way. Actually it is broken even now, but now it is a compile-time error and it is ok.

**Comment by DymOK93** [comment]
Yes, that's right - STL implementations ([MS STL](https://github.com/microsoft/STL/blob/main/stl/inc/ratio#L23) for example) have the same bug and I don't consider it dangerousю

**Comment by DymOK93** [comment]
Closed by #132
